	org 100h
	
	;OBLICZANIE SILNI DO 8! (WŁĄCZNIE)

	XOR AX,AX
	MOV AH,2
	
	MOV DL,10 ;DO NASTĘPNEJ LINII
	INT 21h
	MOV DL,13 ;POWRÓT KARETKI
	INT 21h

	MOV AH,1 ;READKEY
	INT	21H
	
	MOV	AH,0
	SUB	AL,48 ;ODEJMUJEMY OD AL 48 
	PUSH AX	;DO STOSU WCZYTANĄ LICZBE
	CALL sila
	MOV	AH,2
	MOV	DL,32 ;SPACJA
	INT	21H
	
	CALL wysw1
	JMP	koniec
	
sila:
	POP BX ;POBIERAM ZE STOSU WYNIK, ZAPISUJE W BX
	POP AX ;POBIERAM ZE STOSU WYNIK, ZAPISUJE W AX
	MOV CX,AX ;DO CX CHOWAMY ZAWARTOSC AX
	MOV AX,1 ;W AX ZAPISUJEMY 1 (ZEBY MNOZENIE SIE POWIODLO)
	petla:
	MUL CX	;MNOZENIE: AX: AX=CX*AX
	LOOP petla ;ZMNIEJSZAMY CX O 1
	PUSH AX
	PUSH BX	
ret

wysw1:
	POP CX ;POBIERAM ZE STOSU WYNIK, ZAPISUJE W CX
	POP DX ;POBIERAM ZE STOSU WYNIK, ZAPISUJE W DX
	CMP DX,9 
	JNA wysw2
	MOV AX,DX ;WYNIK DO AX
	MOV BX,10 ;PRZEZ CO DZIELIMY
	XOR DX,DX
	DIV BX ;DZIELIMY PRZEZ 10
	PUSH DX ;NA STOS RESZTĘ
	PUSH CX ;NA STOS ADRES POWROTU
	PUSH AX ;NA STOS WYNIK
	PUSH wysw1
	JMP wysw1
	
wysw2:
	MOV AH,2
	ADD DL,48 ;DO WYNIKU DODAJEMY 48
	INT 21h
	PUSH CX
ret


koniec:

	mov	ax, 4C00h
	int	21h